/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author mprad
 */
public class Datos_Generales extends javax.swing.JFrame {

    /**
     * Creates new form Datos_Generales
     */
    private List<Informacion_Paciente> listaPacientes;

    public Datos_Generales() {
        initComponents();
        listaPacientes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAntecedentes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEnfermedades = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAlergias = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMedicamentos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtConsulta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSintomas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtResultados = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMedRecetados = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDosis = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtInstrucciones = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFirma = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtAclaracion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Sistema Registro de Participantes en Investigación Clínica");

        jLabel2.setText("Nombre Completo:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Edad:");

        jLabel4.setText("Género:");

        jLabel5.setText("DNI:");

        jLabel6.setText("Dirección:");

        jLabel7.setText("Teléfono:");

        jLabel8.setText("E-mail:");

        jLabel9.setText("Antecedentes médicos relevantes:");

        jLabel10.setText("Enfermedades Existentes:");

        jLabel11.setText("Alergias conocidas:");

        jLabel12.setText("Medicamentos que toma actualmente:");

        jLabel13.setText("Fecha de la Visita:");

        jLabel14.setText("Hora de la Visita:");

        jLabel15.setText("Motivo de la Consulta:");

        jLabel16.setText("Síntomas o quejas del paciente:");

        jLabel17.setText("Resultados de exámenes:");

        jLabel18.setText("Diagnostico provisional:");

        jLabel19.setText("Tratamiento recomendado:");

        jLabel20.setText("Medicamentos recetados:");

        jLabel21.setText("Dosis y frecuencia:");

        jLabel22.setText("Intrucciones adicionales:");

        jLabel23.setText("Nota del Consentimiento Informado:");

        jLabel24.setText("Firma del Paciente o Representante Legal:");

        jLabel25.setText("Aclaración de los riesgos y beneficios del estudio/IC:");

        jButton1.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Genero", "Identidad", "Direccion ", "Telefono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jButton4.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCorreo))
                                    .addComponent(txtGenero)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAntecedentes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlergias))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSintomas))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedRecetados)
                                    .addComponent(txtDiagnostico)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInstrucciones))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirma))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAclaracion)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtMedRecetados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtAclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(46, 46, 46)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    //Boton agregar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //obtener los valores y hacer los parseos necesarios en caso de que estos sean enteros
            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String genero = txtGenero.getText();
            int identidad = Integer.parseInt(txtIdentidad.getText());
            String direccion = txtDireccion.getText();
            int telefono = Integer.parseInt(txtTelefono.getText());
            String correo = txtCorreo.getText();
            String antecedentes = txtAntecedentes.getText();
            String enfermedades = txtEnfermedades.getText();
            String alergias = txtAlergias.getText();
            String medicamentos = txtMedicamentos.getText();
            String fechaVisita = txtFecha.getText();
            String horaVisita = txtHora.getText();
            String motivoConsulta = txtConsulta.getText();
            String sintomas = txtSintomas.getText();
            String resultados = txtResultados.getText();
            String diagnostico = txtDiagnostico.getText();
            String tratamiento = txtTratamiento.getText();
            String medicamentosRecetados = txtMedRecetados.getText();
            String dosisFrecuencia = txtDosis.getText();
            String instrucciones = txtInstrucciones.getText();
            String notaConsentimiento = txtNota.getText();
            String firmaPaciente = txtFirma.getText();
            String aclaracionRiesgos = txtAclaracion.getText();

            //Creamos los objetos con los datos
            Informacion_Paciente paciente = new Informacion_Paciente(nombre, edad, genero, identidad, direccion, telefono, correo);
            Registro_Medicamentos registroMedicamentos = new Registro_Medicamentos(medicamentosRecetados, dosisFrecuencia, instrucciones);
            Informacion_Visita visita = new Informacion_Visita(fechaVisita, motivoConsulta, sintomas);
            Informacion_Medica informacionMedica = new Informacion_Medica(antecedentes, enfermedades, medicamentos, alergias);
            Datos_Clinicos datosClinicos = new Datos_Clinicos(resultados, "", diagnostico, tratamiento); // Aquí falta la parte de "imagenes"
            Consentimiento_Informado consentimiento = new Consentimiento_Informado(firmaPaciente, aclaracionRiesgos);

            listaPacientes.add(paciente); // Agregar a la lista

            // Actualizar la tabla
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.addRow(new Object[]{nombre, edad, genero, identidad, direccion, telefono, correo}); // Agrega más columnas si es necesario

            // Limpiar campos de texto después de agregar
            txtNombre.setText("");
            txtEdad.setText("");
            txtGenero.setText("");
            txtIdentidad.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
            txtAntecedentes.setText("");
            txtEnfermedades.setText("");
            txtAlergias.setText("");
            txtMedicamentos.setText("");
            txtFecha.setText("");
            txtHora.setText("");
            txtConsulta.setText("");
            txtSintomas.setText("");
            txtResultados.setText("");
            txtDiagnostico.setText("");
            txtTratamiento.setText("");
            txtMedRecetados.setText("");
            txtDosis.setText("");
            txtInstrucciones.setText("");
            txtNota.setText("");
            txtFirma.setText("");
            txtAclaracion.setText("");
        } catch (NumberFormatException e) {
            // Manejar el error si los datos ingresados no son números válidos
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos en los campos de edad, identidad y teléfono.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Manejar otros errores posibles
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al procesar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

// Obtener la fila seleccionada en la tabla
        int selectedRow = jTable2.getSelectedRow();
// Verificar si no se ha seleccionado ninguna fila
        if (selectedRow == -1) {
            // Mostrar un mensaje de advertencia
            JOptionPane.showMessageDialog(this, "Seleccione un registro para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            // Salir de la función
            return;
        }

// Obtener los valores ingresados en los campos de texto
        String nombre = txtNombre.getText();
        String edadStr = txtEdad.getText();
        String genero = txtGenero.getText();
        String identidadStr = txtIdentidad.getText();
        String direccion = txtDireccion.getText();
        String telefonoStr = txtTelefono.getText();
        String correo = txtCorreo.getText();

// Verificar si alguno de los campos obligatorios está vacío
        if (nombre.isEmpty() || edadStr.isEmpty() || genero.isEmpty()
                || identidadStr.isEmpty() || direccion.isEmpty() || telefonoStr.isEmpty()) {
            // Mostrar un mensaje de advertencia
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // Convertir los valores numéricos de texto a números enteros
                int edad = Integer.parseInt(edadStr);
                int identidad = Integer.parseInt(identidadStr);
                int telefono = Integer.parseInt(telefonoStr);

                // Obtener el paciente seleccionado de la lista
                Informacion_Paciente paciente = listaPacientes.get(selectedRow);

                // Actualizar los valores del paciente con los nuevos datos
                paciente.setNombre(nombre);
                paciente.setEdad(edad);
                paciente.setGenero(genero);
                paciente.setIdentidad(identidad);
                paciente.setDireccion(direccion);
                paciente.setTelefono(telefono);
                paciente.setCorreo(correo);
                // Actualizar la tabla con los nuevos valores
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setValueAt(nombre, selectedRow, 0);
                model.setValueAt(edad, selectedRow, 1);
                model.setValueAt(genero, selectedRow, 2);
                model.setValueAt(identidad, selectedRow, 3);
                model.setValueAt(telefono, selectedRow, 4);
                model.setValueAt(correo, selectedRow, 5);
                // Limpieza de campos de texto
                txtNombre.setText("");
                txtEdad.setText("");
                txtGenero.setText("");
                txtIdentidad.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                txtCorreo.setText("");
                txtAntecedentes.setText("");
                txtEnfermedades.setText("");
                txtAlergias.setText("");
                txtMedicamentos.setText("");
                txtFecha.setText("");
                txtHora.setText("");
                txtConsulta.setText("");
                txtSintomas.setText("");
                txtResultados.setText("");
                txtDiagnostico.setText("");
                txtTratamiento.setText("");
                txtMedRecetados.setText("");
                txtDosis.setText("");
                txtInstrucciones.setText("");
                txtNota.setText("");
                txtFirma.setText("");
                txtAclaracion.setText("");

                // Mostrar un mensaje de éxito
                JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                // Mostrar un mensaje si se ingresaron valores no numéricos en campos que deben ser numéricos
                JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos en los campos de edad, identidad y teléfono.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Mostrar un mensaje si ocurre un error al procesar los cambios
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al procesar los cambios.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

//boton eliminar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Primero  obtenemos el valor seleccionado de la tabla para eliminarlo
        int selectedRow = jTable2.getSelectedRow();
        //Detectamos de no haber seleccionado ningun valor para retornar un mensaje
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Obtenemos el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        //Eliminamos la fila seleccionada
        model.removeRow(selectedRow);
        //Y esta misma la eliminamos de la lista que hemos creado
        listaPacientes.remove(selectedRow);

        //Por ultimo enviamos un mensaje de confirmación de la eliminacion del registro
        JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.", "Eliminado", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtEdad.setText("");
        txtGenero.setText("");
        txtIdentidad.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtAntecedentes.setText("");
        txtEnfermedades.setText("");
        txtAlergias.setText("");
        txtMedicamentos.setText("");
        txtFecha.setText("");
        txtHora.setText("");
        txtConsulta.setText("");
        txtSintomas.setText("");
        txtResultados.setText("");
        txtDiagnostico.setText("");
        txtTratamiento.setText("");
        txtMedRecetados.setText("");
        txtDosis.setText("");
        txtInstrucciones.setText("");
        txtNota.setText("");
        txtFirma.setText("");
        txtAclaracion.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos_Generales.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos_Generales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtAclaracion;
    private javax.swing.JTextField txtAlergias;
    private javax.swing.JTextField txtAntecedentes;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEnfermedades;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFirma;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtInstrucciones;
    private javax.swing.JTextField txtMedRecetados;
    private javax.swing.JTextField txtMedicamentos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtResultados;
    private javax.swing.JTextField txtSintomas;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
